### ISSUE TITLE
another instance of hello

### ISSUE THREAD

**Issue by poly-1810** [XenoForce/Exotic-Unofficial#1]

**Comment by XenoForce** [comment]
Hi there, I don't understand your point, or why you insult my work. We can discuss it further, if you want. Just say so, and I will contact you on Discord.

**Comment by XenoForce** [comment]
> *this is literally incredibly useless*

I fully disagree. This is definitely not useless. I have received some very positive feedback from others. 

> *exotic is under active development*

I'm not arguing that.

> *and the indev versions run better than this*

That is debatable.

> *(and are incredibly easy to download and play, for all you idiots out there)*

Well, thanks for calling me (and others) idiots.

Sigh, ...people on the internet sometimes.

**Comment by XenoForce** [comment]
Closed.
