### ISSUE TITLE
a lot of the electric turrets are half broken and some other things

### ISSUE THREAD

**Issue by administrator38** [XenoForce/Exotic-Unofficial#2]
almost all of the electric turrets such as the wavelength or radius shoot even though they have no electricity. the cascadus and empiron reactors are broken

**Comment by XenoForce** [comment]
Thanks for the feedback.

I made changes to both the Cascadus Reactor and the Empiron Reactor. Hopefully, this will solve the power generation issue.

I like the fact that the power turrets can fire without providing power to them. So, I may not change that.

**Comment by XenoForce** [comment]
Closed.
